/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpChecked: typeof import('~icons/ep/checked')['default']
    IEpCrop: typeof import('~icons/ep/crop')['default']
    IEpDataAnalysis: typeof import('~icons/ep/data-analysis')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFailed: typeof import('~icons/ep/failed')['default']
    IEpGoods: typeof import('~icons/ep/goods')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    IEpPostcard: typeof import('~icons/ep/postcard')['default']
    IEpSell: typeof import('~icons/ep/sell')['default']
    IEpShoppingBag: typeof import('~icons/ep/shopping-bag')['default']
    IEpShoppingTrolley: typeof import('~icons/ep/shopping-trolley')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
